#!/usr/bin/env bash

git clone -b v0.12.2 https://github.com/neovim/neovim.git $HOME/personal/neovim
brew install cmake gettext luajit

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
